### ISSUE TITLE
Undeclared dependency Test::Exception

### ISSUE THREAD

**Issue by eserte** [apa-it/xml-newsml-g2#2] opened 2019-10-20 10:13 UTC
Test suite fails if Test::Exception is not installed:
```
Can't locate Test/Exception.pm in @INC (you may need to install the Test::Exception module) (@INC contains: ... .) at t/NewsML_G2_Test_Helpers.pm line 7.
BEGIN failed--compilation aborted at t/NewsML_G2_Test_Helpers.pm line 7.
Compilation failed in require at t/01-News_Item.t line 10.
BEGIN failed--compilation aborted at t/01-News_Item.t line 10.
t/01-News_Item.t ................ 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
... (etc) ...
```

**Comment by eserte** [comment] 2019-10-20 10:14
It seems that this is also another inconsistency between Build.PL and Makefile.PL --- Build.PL lists Test::Exception as a test_requires dependency, Makefile.PL does not. See also #1.

**Comment by jozef** [comment] 2019-10-21 06:44
this is a duplicate of #1

**Closed as completed by jozef** 2019-10-21 06:44 UTC
Labels: duplicate
